FROM ubuntu:xenial

RUN dpkg-reconfigure debconf -f noninteractive -p critical
RUN apt-get update \
    && apt-get install -y \
    clang \
    git \
    build-essential \
    tcl \
    clang-tidy \
    autoconf \
    automake \
    autopoint \
    autotools-dev \
    curl \
    cmake \
    freeglut3-dev \
    g++ \
    libc-ares-dev \
    libcairo2-dev \
    libcppunit-dev \
    libepoxy-dev \
    libev-dev \
    libevdev-dev \
    libevent-dev \
    libexpat1-dev \
    libffi-dev \
    libgbm-dev \
    libgles2-mesa-dev \
    libgmp-dev  \
    libgnutls-dev \
    libinput-dev \
    liblz4-dev  \
    liblzo2-dev \
    libmtdev-dev \
    libpam0g-dev \
    libpciaccess-dev \
    libpcre3-dev \
    libseccomp-dev \
    libsqlite3-dev \
    libssh2-1-dev \
    libssl-dev \
    libstartup-notification0-dev \
    libtool \
    libudev-dev \
    libwacom-dev \
    libxcb-composite0-dev \
    libxcursor-dev \
    libxfont-dev \
    libxkbfile-dev \
    libxml2-dev \
    lzop \
    make \
    nasm \
    ncurses* \
    nettle-dev  \
    opencl-headers \
    pkg-config \
    unzip \
    wayland-protocols \
    x11proto* \
    xfonts-utils \
    xutils-dev \
    zlib1g-dev  \
    uuid-dev \
    default-jre \
    gawk \
    gperf \
    libao-dev \
    libasound2-dev \
    libass-dev \
    libavahi-client-dev \
    libavahi-common-dev \
    libbluetooth-dev \
    libbluray-dev \
    libbz2-dev \
    libcap-dev \
    libcdio-dev \
    libcec-dev \
    libcurl4-openssl-dev \
    libcwiid-dev \
    libdbus-1-dev \
    libegl1-mesa-dev \
    libfontconfig-dev \
    libfreetype6-dev \
    libfribidi-dev \
    libgif-dev \
    libgl-dev \
    libglu-dev \
    libiso9660-dev \
    libjpeg-dev \
    libltdl-dev \
    libmicrohttpd-dev \
    libmpcdec-dev \
    libmysqlclient-dev \
    libnfs-dev \
    libplist-dev \
    libpng-dev \
    libpulse-dev \
    libsmbclient-dev \
    libssh-dev \
    libswscale-dev \
    libtag1-dev \
    libtinyxml-dev \
    libusb-dev \
    libva-dev \
    libvdpau-dev \
    libxmu-dev \
    libxrandr-dev \
    libxslt1-dev \
    libxt-dev \
    lsb-release \
    rapidjson-dev \
    python-dev \
    python-imaging \
    swig \
    yasm \
    perl \
    protobuf-compiler \
    libprotobuf-dev \
    libncurses5-dev \
    libutempter-dev \
    libglib2.0-dev \
    intltool \
    libarchive-dev \
    libjansson-dev \
    valac \
    libfuse-dev \
    qttools5-dev-tools \
    libqt5svg5-dev \
    qtmultimedia5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD lsb_release -a
