sudo apt install autoconf
sudo apt install automake
sudo apt install autopoint
sudo apt install autotools-dev
sudo apt install curl
sudo apt install freeglut3-dev
sudo apt install g++
sudo apt install libc-ares-dev
sudo apt install libcairo2-dev
sudo apt install libcppunit-dev
sudo apt install libepoxy-dev
sudo apt install libev-dev
sudo apt install libevdev-dev
sudo apt install libevent-dev
sudo apt install libexpat1-dev
sudo apt install libffi-dev
sudo apt install libgbm-dev
sudo apt install libgles2-mesa-dev
sudo apt install libgmp-dev 
sudo apt install libgnutls-dev
sudo apt install libinput-dev
sudo apt install liblz4-dev 
sudo apt install liblzo2-dev
sudo apt install libmtdev-dev
sudo apt install libpam0g-dev
sudo apt install libpciaccess-dev
sudo apt install libpcre3-dev
sudo apt install libseccomp-dev
sudo apt install libsqlite3-dev
sudo apt install libssh2-1-dev
sudo apt install libssl-dev
sudo apt install libstartup-notification0-dev
sudo apt install libtool
sudo apt install libudev-dev
sudo apt install libwacom-dev
sudo apt install libxcb-composite0-dev
sudo apt install libxcursor-dev
sudo apt install libxfont-dev
sudo apt install libxkbfile-dev
sudo apt install libxml2-dev
sudo apt install lzop
sudo apt install make
sudo apt install nasm
sudo apt install ncurses*
sudo apt install nettle-dev 
sudo apt install opencl-headers
sudo apt install pkg-config
sudo apt install unzip
sudo apt install wayland-protocols
sudo apt install x11proto*
sudo apt install xfonts-utils
sudo apt install xutils-dev
sudo apt install zlib1g-dev 
